formation/formation/urls.py
from django.contrib import admin
from django.urls import path, include

#upload file
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL ,document_root=settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

formation/music/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

#Route name prefix
app_name = 'music'

urlpatterns = [
    #goes to ex-views.py

    # # /music/
    # path('',views.index, name='index'),
    # # /music/id/
    # url(r'^(?P<album_id>[0-9]+)/$',views.detail, name='detail'),
    #
    # # /music/id/favorite/
    # url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite, name='favorite'),


    # /music/
    url(r'^$',views.IndexView.as_view(), name='index'),

    url(r'^register/$',views.UserFormView.as_view(), name='register'),
    # /music/id/
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='detail'),
    # /music/album/add/
    url(r'^album/add/$',views.AlbumCreate.as_view(), name='album-add'),
    # /music/album/2/
    url(r'^album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(), name='album-update'),
    # /music/album/2/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(), name='album-delete'),

]

formation/music/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail',kwargs={ 'pk':self.pk })

    def __str__(self):
        return self.artist + '-' + self.album_title + '-' + self.genre + '-' + self.album_logo.url

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    if_favorite = models.BooleanField(default=False)


    def __str__(self):
        return self.if_favorite

formation/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [ 'username' , 'email' , 'password' ]

formation/music/views.py
from django.views import generic
from .models import Album
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
#login
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate , login
from django.views.generic import View
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()



class DetailView(generic.DeleteView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist' , 'album_title' , 'genre' , 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist' , 'album_title' , 'genre' , 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

#login
class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    #display blank form (get)
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name , {'form':form})

    #process form data (post)
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            #cleaned (normalize data)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #return User object if credentials are correct
            user = authenticate(username=username , password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

formation/music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block title %}Add a new album{% endblock %}

{% block body %}


<form action=""  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'music/form-template.html' %}
    <div>
        <button type="submit">Submit</button>
    </div>

</form>
{% endblock %}

formation/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
</head>
<body>
<nav><h1 class="header">This is my commun header</h1>
    <a href="{% url 'music:album-add' %}">Add Album</a>
</nav>



{% block body %}
<!-- this is base template -->
{% endblock %}
</body>
</html>

formation/music/templates/music/detail.html
{% extends 'music/base.html'  %}
{% block title %}
detail
{% endblock %}
{% block body %}
<!-- this is detail template -->
    <img src="{{album.album_logo.url}}" >

    <h1>{{album.album_title}}</h1>

    <h3>{{album.artist}}</h3>

    {% if error_message %}
    <p><strong>{{error_message}}</strong></p>
    {% endif %}
    <ul>
    {% for song in album.song_set.all %}
        <li>{{song.song_title}}</li>
    {% endfor %}
    </ul>
{% endblock %}

formation/music/templates/music/form-template.html
{% for field in form %}
    <div>
        <p><strong>{{ field.errors }}</strong></p>
        <label>{{field.label_tag }}</label>
        <div>{{ field }}</div>
    </div>
{% endfor %}

formation/music/templates/music/index.html
{% extends 'music/base.html'  %}
{% block title %}
home
{% endblock %}
{% block body %}
<!-- this is index template -->
    <h1>this is Home page</h1>
    {% if object_list %}
        <ul class="test">
            {% for album in object_list %}
            <li><a href="{% url 'music:detail' album.id %}">{{album.album_title}}</a></li>
            <li><img src="{{ album.album_logo.url }}"></li>
            <form action="{% url 'music:album-delete' album.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="album_id" value="{{album_id}}">
                <button type="submit">Delete</button>
            </form>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You dont have any albums</h3>
    {% endif %}
{% endblock %}

formation/music/templates/music/registration_form.html
{% extends 'music/base.html' %}

{% block title %}Register{% endblock %}

{% block body %}


<form action=""  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'music/form-template.html' %}
    <div>
        <button type="submit">Submit</button>
    </div>

</form>
{% endblock %}